# Universidad de la Laguna
# Escuela Superior de Ingeniería y Tecnología
# Grado en Ingeniería Informática
# Asignatura: Computabilidad y Algoritmia
# Curso: 2º
# Practica 4: Expresiones Regulares
# Autor: Fabrizzio Daniell Perilli Martin
# Correo: alu0101138589@ull.edu.es
# Fecha: 08/10/2022
# Archivo: MakeFile
#             ...
# Referencias:
# Historial de revisiones:
# Fecha: 02/11/2022 - Versión: 1.0 - Descripción: Creación del código.

FILES= *.cc
CXXFLAGS= -Wall -std=c++17 -ggdb

all:
	g++ $(CXXFLAGS) $(FILES) -o grammar2CNF

clean:
	rm -rf grammar2CNF 
	rm -rf *.o
