# Universidad de la Laguna
# Escuela Superior de Ingeniería y Tecnología
# Grado en Ingeniería Informática
# Asignatura: Computabilidad y Algoritmia
# Curso: 2º
# Practica 2: Operaciones con lenguajes
# Autor: Fabrizzio Daniell Perilli Martin
# Correo: alu0101138589@ull.edu.es
# Fecha: 11/10/2022
# Archivo Makefile
#             ...
# Referencias:
# Historial de revisiones:
# Fecha: 7/10/2022 - Versión: 1.0 - Descripción: Creación del código.


FILES= *.cc
CXXFLAGS= -Wall -std=c++17 -ggdb


all: practica

Inicio:
	@echo $(C) 

practica: $(F) Inicio
	g++ $(CXXFLAGS) $(FILES) -o p02_languages

clean:
	rm -rf p02_languages 
	rm -rf *.o