# Universidad de la Laguna
# Escuela Superior de Ingeniería y Tecnología
# Grado en Ingeniería Informática
# Asignatura: Computabilidad y Algoritmia
# Curso: 2º
# Practica 1: Simbolos, alfabetos y cadena
# Autor: Fabrizzio Daniell Perilli Martin
# Correo: alu0101138589@ull.edu.es
# Fecha: 5/10/2022
# Archivo Makefile: programa cliente.
#             ...
# Referencias:
# Historial de revisiones:
# Fecha: 28/09/2022 - Versión: 1.0 - Descripción: Creación del código.


FILES= *.cc
CXXFLAGS= -Wall -std=c++17 -ggdb


all: practica

Inicio:
	@echo $(C) 

practica: $(F) Inicio
	g++ $(CXXFLAGS) $(FILES) -o p01_strings

clean:
	rm -rf p01_strings 
	rm -rf *.o