# Universidad de la Laguna
# Escuela Superior de Ingeniería y Tecnología
# Grado en Ingeniería Informática
# Asignatura: Computabilidad y Algoritmia
# Curso: 2º
# Practica 3: Calculadora de lengaujes formales
# Autor: Fabrizzio Daniell Perilli Martin
# Correo: alu0101138589@ull.edu.es
# Fecha: 18/10/2022
# Archivo Makefile
#             ...
# Referencias:
# Historial de revisiones:
# Fecha: 12/10/2022 - Versión: 1.0 - Descripción: Creación del código.


FILES= *.cc
CXXFLAGS= -Wall -std=c++17 -ggdb


all: practica

Inicio:
	@echo $(C) 

practica: $(F) Inicio
	g++ $(CXXFLAGS) $(FILES) -o p03_calculator

clean:
	rm -rf p03_calculator 
	rm -rf *.o